services:
  - type: web
    name: backendroofing-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm install
      chmod +x ../setup.sh
      ../setup.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
